//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buncis.Framework.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Redirections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Redirections() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buncis.Framework.Core.Resources.Redirections", typeof(Redirections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/NotFound.aspx.
        /// </summary>
        public static string Page_404 {
            get {
                return ResourceManager.GetString("Page_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Articles/Detail.aspx.
        /// </summary>
        public static string Page_ArticleDetail {
            get {
                return ResourceManager.GetString("Page_ArticleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bPanel/Dashboard.aspx.
        /// </summary>
        public static string Page_Buncis_Dashboard {
            get {
                return ResourceManager.GetString("Page_Buncis_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/bPanel/.
        /// </summary>
        public static string Page_Buncis_Login {
            get {
                return ResourceManager.GetString("Page_Buncis_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/DailyBread/Detail.aspx.
        /// </summary>
        public static string Page_DailyBreadDetail {
            get {
                return ResourceManager.GetString("Page_DailyBreadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/DynamicPage.aspx.
        /// </summary>
        public static string Page_DynamicPage {
            get {
                return ResourceManager.GetString("Page_DynamicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Home.aspx.
        /// </summary>
        public static string Page_Home {
            get {
                return ResourceManager.GetString("Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/News/Detail.aspx.
        /// </summary>
        public static string Page_NewsDetail {
            get {
                return ResourceManager.GetString("Page_NewsDetail", resourceCulture);
            }
        }
    }
}
