//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buncis.Web.bPanel.Pages {
    
    
    public partial class List {
        
        /// <summary>
        /// pageWysiwygToolbar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Buncis.Web.UserControls.Component.WysiwygToolbar pageWysiwygToolbar;
    }
}
